# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/graphql-hooks
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - run:
          name: 'Generate Key'
          command: echo "export GRAPHQL_HOOKS_CHECKSUM=$(~/graphql-hooks/.circleci/generate_key.sh)" >> $BASH_ENV

      - run:
          name: "What is the GRAPHQL_HOOKS_CHECKSUM?"
          command: echo ${GRAPHQL_HOOKS_CHECKSUM}

      - restore_cache:
          key: graphql-hooks-key-{{ .Environment.GRAPHQL_HOOKS_CHECKSUM }}

      - run: npm install

      - save_cache:
          key: graphql-hooks-key-{{ .Environment.GRAPHQL_HOOKS_CHECKSUM }}
          paths:
            - ~/graphql-hooks/node_modules
            - ~/graphql-hooks/packages/graphql-hooks/node_modules
            - ~/graphql-hooks/packages/graphql-hooks-memcache/node_modules
            - ~/graphql-hooks/packages/graphql-hooks-ssr/node_modules

      - run:
          name: 'JavaScript Linter'
          command: npm run eslint -- --format junit -o reports/junit/js-lint-results.xml

      - run: npm run test:coverage

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

      - run: npm run coveralls
  acceptance-tests:
    working_directory: ~/graphql-hooks
    environment:
      BROWSERSTACK_PARALLEL_RUNS: '5'
      BROWSERSTACK_USE_AUTOMATE: '1'
      BROWSERSTACK_PROJECT_NAME: 'graphql-hooks'
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - run:
          name: 'Generate Key'
          command: echo "export GRAPHQL_HOOKS_CHECKSUM=$(~/graphql-hooks/.circleci/generate_key.sh)" >> $BASH_ENV

      - restore_cache:
          key: graphql-hooks-key-{{ .Environment.GRAPHQL_HOOKS_CHECKSUM }}

      - run: npm install

      - save_cache:
          key: graphql-hooks-key-{{ .Environment.GRAPHQL_HOOKS_CHECKSUM }}
          paths:
            - ~/graphql-hooks/node_modules
            - ~/graphql-hooks/packages/graphql-hooks/node_modules
            - ~/graphql-hooks/packages/graphql-hooks-memcache/node_modules
            - ~/graphql-hooks/packages/graphql-hooks-ssr/node_modules

      - run: npm run test:acceptance:ci

      - store_test_results:
          path: /tmp/acceptance-test-results
